### ISSUE TITLE
Publish package?

### ISSUE THREAD

**Issue by jeffcole** [xarvh/elm-audio#4]
Nice work here, thanks!

It looks like there is a 1.0.0 release, but the package doesn't seem to be on http://package.elm-lang.org/?

I was wondering if you have plans to publish it so that it's easier for folks to play with it and contribute?

Thanks again!

**Comment by xarvh** [comment]
@jeffcole I wish I could.
Thing is, `elm-audio` has by necessity unsafe native js code, @evancz doesn't want third-party native code and there is no process or policy available for accepting such code, even if elm-audio is tested out of its nose.

I am not sure how and if @evancz intends to address this, but you can ask here https://elmlang.slack.com/messages/elm-dev/

**Comment by jeffcole** [comment]
@xarvh I see, I suppose that makes sense.

In any case, I believe this package will be useful to people, so thanks for authoring it, and for your helpful response!

**Comment by xarvh** [comment]
So glad someone is using it. =)
