### ISSUE TITLE
update it to elm 0.18

### ISSUE THREAD

**Issue by gabrielperales** [xarvh/elm-audio#5]

**Comment by xarvh** [comment]
Wouldn't make much sense.
Ports are easier to use.

**Comment by gabrielperales** [comment]
I'm going to try to do it by myself,  just to keep learning elm. But is good to know your thoughts about use ports instead. 

Thank you

**Comment by xarvh** [comment]
Good luck.
If you want to see how I'm doing audio now, you can check https://github.com/xarvh/elm-haifisch

**Comment by gabrielperales** [comment]
Thanks!!  Your repos looks amazing!!  I'll have a deeply look to them :)
